# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - goerli

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Generate zip file
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    # Deploy to both environments on ELB
    - name: Beanstalk Deploy for Lighthouse
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
        aws_secret_key: ${{secrets.AWS_SECRET_KEY}}
        application_name: ${{secrets.APP_NAME}}
        environment_name: ${{secrets.APP_NAME}}-goerli
        region: us-east-1
        version_label: "goerli-${{github.sha}}"
        deployment_package: deploy.zip

    - name: Deployed!
      run: echo "Geth deployed to EB"